FROM fedora:40@sha256:4e007f288dce23966216be81ef62ba05d139b9338f327c1d1c73b7167dd47312 as builder

RUN dnf -y install gcc-c++ git findutils make cmake strace gdb util-linux
COPY . /tmp/pcm
RUN --mount=type=cache,target=/tmp/pcm/build cd /tmp/pcm/build && cmake -D CMAKE_BUILD_TYPE=Debug .. && cmake --build . -t pcm pcm-sensor-server pcm-tpmi -j && cp -v /tmp/pcm/build/bin/pcm* /bin/
#ENV PCM_NO_PERF=1
