%define _name   pcm

Name:		    %{_name}
Version:        %{?version}%{!?version:9.9.9}
Release: 	    1%{?dist}
Summary:	    LightOS kernel infrastructure
License: 	    Proprietary
Group:		    Development
Vendor:   	    Lightbits Labs LTD
Provides:	    %{_name}
BuildRoot:	    %{build_root}
ExclusiveArch: 	x86_64

%description
LightOS infrastructure: pcm.

%install
mkdir -p %{buildroot}%{_bindir}
cp %{_builddir}/pcm-sensor.x %{buildroot}%{_bindir}/pcm-sensor.x
cp %{_builddir}/pcm-pcie.x %{buildroot}%{_bindir}/pcm-pcie.x
cp %{_builddir}/pcm-msr.x %{buildroot}%{_bindir}/pcm-msr.x
cp %{_builddir}/pcm-memory.x %{buildroot}%{_bindir}/pcm-memory.x
cp %{_builddir}/pcm-tsx.x %{buildroot}%{_bindir}/pcm-tsx.x
cp %{_builddir}/pcm-core.x %{buildroot}%{_bindir}/pcm-core.x
cp %{_builddir}/pcm-iio.x %{buildroot}%{_bindir}/pcm-iio.x
cp %{_builddir}/pcm-numa.x %{buildroot}%{_bindir}/pcm-numa.x
cp %{_builddir}/pcm.x %{buildroot}%{_bindir}/pcm.x
cp %{_builddir}/pcm-power.x %{buildroot}%{_bindir}/pcm-power.x
cp %{_builddir}/pcm-lspci.x %{buildroot}%{_bindir}/pcm-lspci.x

%files
%defattr(-,root,root,-)
%{_bindir}/pcm-sensor.x
%{_bindir}/pcm-pcie.x
%{_bindir}/pcm-msr.x
%{_bindir}/pcm-memory.x
%{_bindir}/pcm-tsx.x
%{_bindir}/pcm-core.x
%{_bindir}/pcm-iio.x
%{_bindir}/pcm-numa.x
%{_bindir}/pcm.x
%{_bindir}/pcm-power.x
%{_bindir}/pcm-lspci.x

%pre
if [ -f /etc/lightbox/lb_install_protection ]
then
    echo "Lightos did not shutdown gracefully, cannot install rpm"
    exit 1
fi

%clean
rm -rf %{buildroot}

%changelog
* Wed Jun 19 2019 Yogev Cohen <yogev@lightbitslabs.com>
- create a spec file for package which is not autogenerated.

* Tue May 8 2018 Anton Eidelman <anton@lightbitslabs.com>
- auto generated rpm

