apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "pcm.fullname" . }}-test-connection"
  #name: pcm
  # labels:
  #{{/*   {{- include "pcm.labels" . | nindent 4 }} */}}
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  containers:
    - name: wget
      image: busybox
      command: 
      - 'sh' 
      - '-c'
      - 'sleep 15; ping {{ include "pcm.fullname" . }}-test-connection.{{ .Release.Namespace }}.svc.cluster.local -t 1 -W 1 -w 1 -c 1 ; wget -T 15 -S {{ include "pcm.fullname" . }}-test-connection.{{ .Release.Namespace }}.svc.cluster.local:9739/metrics -O - | grep Measurement_Interval_in_us'
  restartPolicy: Never
