{
 "title": "Memory Traffic - 1",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Socket0 DRAM reads (Mbytes/sec)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"Sockets_0_Uncore_Uncore Counters_DRAM Reads\")/1000000 FROM \"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "Sockets_0_Uncore_Uncore Counters_DRAM Reads"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Socket0 DRAM writes (MBytes/sec)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"Sockets_0_Uncore_Uncore Counters_DRAM Writes\")/1000000 FROM \"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Socket1 DRAM reads (Mbytes/sec)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"Sockets_1_Uncore_Uncore Counters_DRAM Reads\")/1000000 FROM \"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Socket1 DRAM writes (MBytes/sec)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"Sockets_1_Uncore_Uncore Counters_DRAM Writes\")/1000000 FROM \"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPI Incoming Data Traffic",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "Socket0 UPI0 (%)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"QPI/UPI Links_QPI Counters Socket 0_Utilization Incoming Data Traffic On Link 0\")*100 FROM \"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "QPI/UPI Links_QPI Counters Socket 0_Utilization Incoming Data Traffic On Link 0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Socket0 UPI1 (%)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"QPI/UPI Links_QPI Counters Socket 0_Utilization Incoming Data Traffic On Link 1\")*100 FROM \"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Socket1 UPI0 (%)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"QPI/UPI Links_QPI Counters Socket 1_Utilization Incoming Data Traffic On Link 0\")*100 FROM \"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Socket1 UPI1 (%)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"QPI/UPI Links_QPI Counters Socket 1_Utilization Incoming Data Traffic On Link 1\")*100 FROM \"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UPI Outgoing Data and Non-Data Traffic",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 15 },
   "targets": [
    {
     "alias": "Socket0 UPI0 (%)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"QPI/UPI Links_QPI Counters Socket 0_Utilization Outgoing Data And Non-Data Traffic On Link 0\")*100 FROM \"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       {
        "params": [
         "QPI/UPI Links_QPI Counters Socket 0_Utilization Outgoing Data And Non-Data Traffic On Link 0"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Socket0 UPI1 (%)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"QPI/UPI Links_QPI Counters Socket 0_Utilization Outgoing Data And Non-Data Traffic On Link 1\")*100 FROM \"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Socket1 UPI0 (%)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"QPI/UPI Links_QPI Counters Socket 1_Utilization Outgoing Data And Non-Data Traffic On Link 0\")*100 FROM \"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Socket1 UPI1 (%)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"QPI/UPI Links_QPI Counters Socket 1_Utilization Outgoing Data And Non-Data Traffic On Link 1\")*100 FROM \"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}