name: coverity-linux-and-python-report

on: [workflow_dispatch, workflow_call]

permissions:
  contents: read

jobs:
  build:

    runs-on: ci-kw-linux
    if: ${{ github.repository != 'intel/pcm' }}

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
      with:
        egress-policy: audit

    - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      with:
        submodules: recursive

    - name: coverity-python
      run: |
        ci-cov-python.sh

    - name: coverity-linux
      run: |
        mkdir build
        cd build
        cmake ..
        ci-cov-linux.sh

    - name: coverity-linux-and-python-report
      run: |
        ci-cov-linux-report.sh PCM.linux.and.python

    - name: upload-artifact
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: coverity-linux-and-python-report-${{ github.sha }}
        path: "*-Report.pdf"
