name: fuzz-micro-job

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

permissions:
  contents: read

jobs:
  fuzz:
    runs-on: ci-test
    if: ${{ github.repository != 'intel/pcm' }}

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
      with:
        egress-policy: audit

    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      with:
        submodules: recursive

    - name: Build and test
      run: |
        cmake --version
        set -o pipefail
        mkdir build
        cd build
        bash ${{ github.workspace }}/tests/fuzz.sh 5 2>&1 | tee fuzz-log.txt
        cd ..

    - name: Show report
      run: |
        cat build/report.txt
        echo "Fuzzing completed"

    - name: upload-artifact
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: fuzz-log-${{ github.sha }}
        path: "build/fuzz-log.txt"


