name: g++ 7 build

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ci-gcc7
    if: ${{ github.repository != 'intel/pcm' }}

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
      with:
        egress-policy: audit

    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
    - name: install simdjson
      uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      with:
        repository: simdjson/simdjson
        path: src/simdjson
    - name: Configure CMake
      run: |
        cmake --version
        rm -rf ${{ github.workspace }}/build && mkdir ${{ github.workspace }}/build
        cd ${{ github.workspace }}/build
        cmake -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/build ..
    - name: Build
      run: |
        g++ --version
        cd ${{ github.workspace }}/build
        make -j$(nproc)
    - name: Install
      run: |
        cd ${{ github.workspace }}/build
        make install -j$(nproc)
    - name: Diagnostic
      run: date