name: g++ 5 build

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ci-gcc5
    if: ${{ github.repository != 'intel/pcm' }}

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
      with:
        egress-policy: audit

    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - name: install simdjson
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      with:
        repository: simdjson/simdjson
        path: src/simdjson
    - name: Configure CMake
      run: |
        cmake --version
        rm -rf ${{ github.workspace }}/build && mkdir ${{ github.workspace }}/build
        cd ${{ github.workspace }}/build
        cmake -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/build ..
    - name: Build
      run: |
        g++ --version
        cd ${{ github.workspace }}/build
        make -j$(nproc)
    - name: Install
      run: |
        cd ${{ github.workspace }}/build
        make install -j$(nproc)
    - name: upload-artifact
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: PCMforLinuxGCC5
        path: build/bin/*
