name: windows-ip

on: [workflow_dispatch, workflow_call]

permissions:
  contents: read

jobs:
  build:

    runs-on: ci-windows
    if: ${{ github.repository != 'intel/pcm' }}

    steps:
    
    - name: Harden Runner
      uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
      with:
        egress-policy: audit

    - name: windows-ip
      run: |
        ipconfig
