name: MSVC Windows build

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

env:
  BUILD_TYPE: Release

permissions:
  contents: read

jobs:
  build:

    runs-on: ci-windows
    if: ${{ github.repository != 'intel/pcm' }}

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
      with:
        egress-policy: audit

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        submodules: recursive
    - name: Configure CMake
      run: |
        if (Test-Path ${{github.workspace}}\build){ Remove-Item ${{github.workspace}}\build -Recurse }
        cmake -B ${{github.workspace}}\build
    - name: Build
      run: |
        cmake --build ${{github.workspace}}\build --config ${{env.BUILD_TYPE}} --parallel
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2.0.0
    - name: Build MSR driver
      run: |
        chdir ${{github.workspace}}\src\WinMSRDriver
        msbuild MSR.vcxproj /p:Configuration=Release,Platform=x64 /t:Clean,Build /m
    - name: upload-artifact
      uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
      with:
        name: PCMforWindows
        path: build/bin/**/*
