name: windows-ip

on: [workflow_dispatch, workflow_call]

permissions:
  contents: read

jobs:
  build:

    runs-on: ci-windows
    if: ${{ github.repository != 'intel/pcm' }}

    steps:
    
    - name: Harden Runner
      uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
      with:
        egress-policy: audit

    - name: windows-ip
      run: |
        ipconfig
