name: Mac OS X scan-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: macOS-13

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
      with:
        egress-policy: audit

    - name: Select Xcode 14.3.1
      run: sudo xcode-select -s /Applications/Xcode_14.3.1.app/Contents/Developer

    - name: Set SDKROOT and verify kernel headers
      shell: bash
      run: |
          SDKROOT="$(xcrun --sdk macosx --show-sdk-path)"
          echo "SDKROOT=$SDKROOT" >> "$GITHUB_ENV"
          test -f "$SDKROOT/System/Library/Frameworks/Kernel.framework/Headers/IOKit/IOLib.h" || {
            echo "Kernel IOLib.h not found under SDK: $SDKROOT" >&2
            exit 1
          }

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        submodules: recursive
    - name: cmake
      run: |
        rm -rf ${{ github.workspace }}/build
        $(brew --prefix llvm@15)/bin/scan-build cmake -B ${{ github.workspace }}/build -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}
    - name: make
      run: |
        cd ${{ github.workspace }}/build
        $(brew --prefix llvm@15)/bin/scan-build --exclude src/simdjson --status-bugs make -j
