name: stats-cron-job

on:
  schedule:
    - cron: '30 23 * * 2'

permissions:
  contents: read

jobs:
  stats:
    runs-on: ubuntu-20.04
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
      with:
        egress-policy: audit

    - name: stats
      run: |
        curl https://hetthbszh0.execute-api.us-east-2.amazonaws.com/default/pcm-clones
