name: stats-cron-job

on:
  schedule:
    - cron: '30 23 * * 2'

permissions:
  contents: read

jobs:
  stats:
    runs-on: ubuntu-20.04
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
      with:
        egress-policy: audit

    - name: stats
      run: |
        curl https://hetthbszh0.execute-api.us-east-2.amazonaws.com/default/pcm-clones
