name: stats-cron-job

on:
  schedule:
    - cron: '30 23 * * 2'

permissions:
  contents: read

jobs:
  stats:
    runs-on: ubuntu-20.04
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit

    - name: stats
      run: |
        curl https://hetthbszh0.execute-api.us-east-2.amazonaws.com/default/pcm-clones
